name: Build NDS File
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build NDS
        run: make

      - name: Upload NDS
        uses: actions/upload-artifact@v4
        with:
          name: DSpTracker.nds
          path: ./DSpTracker.nds
          if-no-files-found: error
        
